### ISSUE TITLE
question

### ISSUE THREAD

**Issue by gggin** [netheril96/autojsoncxx#11]
Can I have a rapidjson::Document in Person(my own define class)

Person.hpp

```c++
Persion p;
```
p.tree is a std::shared_ptr\<rapidjson::Document\> or std::unique_ptr\<rapidjson::Document\>?
or p.tree is a std::shared_ptr\<rapidjson::Value\>

Thanks!

**Comment by netheril96** [comment]
You probably can use `std::unique_ptr<rapidjson::Document>`, but it only works if that node is a valid JSON document, that is, an array or object. `rapidjson::Value` is not supported for now, but it should not be hard to add.

**Comment by gggin** [comment]
so good! tks!
