### ISSUE TITLE
utf8-with-bom

### ISSUE THREAD

**Issue by gggin** [netheril96/autojsoncxx#13]
json schema file do not support utf8-with-bom type

**Comment by netheril96** [comment]
Why do you need utf8 with BOM anyway? BOM is useless in conjunction with UTF8.

**Comment by gggin** [comment]
In one team, many users. If they use UTF8 With BOM the error message will let them confused.
Then try to fix json error, but it just an BOM error!

**Comment by netheril96** [comment]
Are you on Windows?

**Comment by gggin** [comment]
Yes

**Comment by netheril96** [comment]
Implemented in d7df6f8
