### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by gggin** [netheril96/autojsoncxx#14]
why not add a way to support {"a": 1, "b":"c"}(one map multitype)

with std::tuple we can generate ["1", 2, 1.0, {...}]

but how to implement {"a": 1, "b":"c"}

**Comment by netheril96** [comment]
`std::tuple` is in the standard library. No such thing for a variant map.

A map of dynamic type is called a JSON. Simply use normal JSON value for that.

**Comment by netheril96** [comment]
The raison d'etre of `autojsoncxx` is static typing. While it supports `rapidjson::Document` type, which can be a dynamic map, it is not what it is intended to be used.
