### ISSUE TITLE
Error while build

### ISSUE THREAD

**Issue by Bharatesh** [netheril96/autojsoncxx#8]
Hi 

I am new to C++ programming. While building project I came across following error.

error: 'autojsoncxx' has not been declared

I know, its a wrong place to raise such questions. But any help or hint would be wonderful. I also includes project folders in "Project Includes" and I am using eclipse Luna.

Thanks and Regards

**Comment by netheril96** [comment]
The include path is wrong?

**Comment by netheril96** [comment]
Or did you include the generated header before compilation?

**Comment by Bharatesh** [comment]
Thank you very much for replies.

I am doing following steps.
1. IDE is eclipse Luna C++.
2. I created a test projct.
3. Created Includes directory in src folder of project and copied all header files.
4. Then build the project.
5. I am presently running the example given in following tutorial.
     http://netheril96.github.io/autojsoncxx/tutorial/
The serialization example. 
6. I also included folders in include section of the project. 

Thanks and Regards
Bharatesh Regoudar.

**Comment by netheril96** [comment]
@Bharatesh 

What is your C++ compiler version? Did you turn on c++11 in your project settings?

**Comment by Bharatesh** [comment]
Once again thank your feedback. Yes before c++11 was not activated. After activation no errors. But now make giving error like. recipe for make file failed.

**Comment by netheril96** [comment]
@Bharatesh Can you post more detailed error message? Turn on all verbose options. I need more information.

**Comment by Bharatesh** [comment]
Please find detals information after enabling verbose mode. 

Description	Resource	Path	Location	Type
Function 'max' could not be resolved	base.hpp	/TestProject/src/include/autojsoncxx	line 238	Semantic Error
Function 'max' could not be resolved	base.hpp	/TestProject/src/include/autojsoncxx	line 246	Semantic Error
Function 'max' could not be resolved	base.hpp	/TestProject/src/include/autojsoncxx	line 255	Semantic Error
Function 'max' could not be resolved	base.hpp	/TestProject/src/include/autojsoncxx	line 295	Semantic Error
Function 'max' could not be resolved	base.hpp	/TestProject/src/include/autojsoncxx	line 303	Semantic Error
Function 'max' could not be resolved	base.hpp	/TestProject/src/include/autojsoncxx	line 346	Semantic Error
Function 'min' could not be resolved	base.hpp	/TestProject/src/include/autojsoncxx	line 247	Semantic Error
make: *** [src/TestProject.o] Error 1	TestProject		 	C/C++ Problem
recipe for target 'src/TestProject.o' failed	subdir.mk	/TestProject/Debug/src	line 18	C/C++ Problem
Symbol 'numeric_limits' could not be resolved	base.hpp	/TestProject/src/include/autojsoncxx	line 238	Semantic Error
Symbol 'numeric_limits' could not be resolved	base.hpp	/TestProject/src/include/autojsoncxx	line 246	Semantic Error
Symbol 'numeric_limits' could not be resolved	base.hpp	/TestProject/src/include/autojsoncxx	line 247	Semantic Error
Symbol 'numeric_limits' could not be resolved	base.hpp	/TestProject/src/include/autojsoncxx	line 255	Semantic Error
Symbol 'numeric_limits' could not be resolved	base.hpp	/TestProject/src/include/autojsoncxx	line 295	Semantic Error
Symbol 'numeric_limits' could not be resolved	base.hpp	/TestProject/src/include/autojsoncxx	line 303	Semantic Error
Symbol 'numeric_limits' could not be resolved	base.hpp	/TestProject/src/include/autojsoncxx	line 346	Semantic Error

**Comment by Bharatesh** [comment]
Fixed Semantic Errors after enabling proper binary parsers.
But still make fails with following messages.

make: *** [src/TestProject.o] Error 1 TestProject C/C++ Problem
recipe for target 'src/TestProject.o' failed subdir.mk /TestProject/Debug/src line 18 C/C++ Problem

**Comment by netheril96** [comment]
@Bharatesh I pushed a new commit. Try pulling it down and test again.

**Comment by Bharatesh** [comment]
@netheril96 I tried. Now recipe for target message is gone. But appeared following one.

Description	Resource	Path	Location	Type
make: *** No rule to make target 'all'.  Stop.	JsonSerializor		 	C/C++ Problem

**Comment by Bharatesh** [comment]
make: *** No targets specified and no makefile found.  Stop.	JsonSerializor		 	C/C++ Problem

**Comment by netheril96** [comment]
> make: *** No rule to make target 'all'.

That seems to be a problem with your own makefile.

**Comment by Bharatesh** [comment]
Thank you. For support.
